# Generated by Django 5.1.3 on 2024-11-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('opis', models.TextField()),
                ('ikona', models.ImageField(default=None, upload_to='media/ikony_firm')),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=256)),
                ('nazwisko', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('opis', models.TextField()),
                ('cena', models.FloatField()),
                ('zdjecie', models.ImageField(default=None, upload_to='media/zdjecia_produktow')),
                ('firma', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jeszczedrozej.firma')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeszczedrozej.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentarz', models.TextField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeszczedrozej.klient')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeszczedrozej.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('data_dostarczenia', models.DateTimeField()),
                ('adres_dostawy', models.TextField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeszczedrozej.klient')),
                ('produkty', models.ManyToManyField(to='jeszczedrozej.produkt')),
            ],
        ),
    ]
