# Generated by Django 5.1.3 on 2024-11-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeszczedrozej', '0002_klient_groups_klient_is_active_klient_is_staff_and_more'),
        ('jeszczedrozej', '0002_klient_haslo_alter_klient_nazwisko_and_more'),
    ]

    operations = [
    ]
