# Generated by Django 5.1.3 on 2024-11-27 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('opis', models.TextField()),
                ('ikona', models.ImageField(blank=True, null=True, upload_to='media/ikony_firm')),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=256)),
                ('opis', models.TextField()),
                ('cena', models.FloatField()),
                ('srednia_ocen', models.FloatField()),
                ('zdjecie', models.ImageField(blank=True, null=True, upload_to='media/zdjecia_produktow')),
                ('firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alledrogo.firma')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alledrogo.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentarz', models.TextField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alledrogo.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('data_dostarczenia', models.DateTimeField()),
                ('adres_dostawy', models.TextField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produkty', models.ManyToManyField(to='alledrogo.produkt')),
            ],
        ),
    ]
