# Generated by Django 5.1.3 on 2024-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena_znizkowa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='srednia_ocen',
            field=models.FloatField(default=0),
        ),
    ]
