# Generated by Django 5.1.3 on 2024-11-27 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0002_produkt_cena_znizkowa_alter_produkt_srednia_ocen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('produkty', models.ManyToManyField(to='alledrogo.produkt')),
            ],
        ),
    ]
