# Generated by Django 5.1.3 on 2024-11-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0003_koszyk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='cena_znizkowa',
        ),
    ]
