# Generated by Django 5.1.1 on 2024-11-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0004_remove_produkt_cena_znizkowa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koszyk',
            name='produkty',
        ),
        migrations.CreateModel(
            name='PozycjaKoszyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('koszyk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='alledrogo.koszyk')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alledrogo.produkt')),
            ],
        ),
    ]
