# Generated by Django 5.1.3 on 2024-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0006_firma_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='imie',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='kod_pocztowy',
            field=models.CharField(default='brak', max_length=6),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='miasto',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='nazwisko',
            field=models.CharField(default='brak', max_length=100),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='notatki',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='numer_telefonu',
            field=models.CharField(default='brak', max_length=15),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='ulica',
            field=models.CharField(default='brak', max_length=255),
        ),
    ]
