# Generated by Django 5.1.3 on 2024-11-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0007_zamowienie_imie_zamowienie_kod_pocztowy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='adres_dostawy',
        ),
    ]
