# Generated by Django 5.1.3 on 2024-12-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alledrogo', '0008_remove_zamowienie_adres_dostawy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alledrogo.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alledrogo.zamowienie')),
            ],
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='produkty_z_iloscia',
            field=models.ManyToManyField(related_name='zamowienia_z_iloscia', through='alledrogo.PozycjaZamowienia', to='alledrogo.produkt'),
        ),
    ]
